### ISSUE TITLE
pip installation does not work on macOS

### ISSUE THREAD

**Issue by pmla** [pmla/auguste#5]
Making a separate issue out of the problem described in #4:

>... the pip install doesn't work on macOS without manually modifying the setup.py to set `MACOSX_DEPLOYMENT_TARGET`.

@mkhorton, can you paste your modified `setup.py`? I am not a macOS user but I will modify the travis CI script so that this gets tested properly.

**Comment by mkhorton** [comment]
Sure thing, so I copied the method used by pandas: https://github.com/pandas-dev/pandas/blob/master/setup.py

This is:

```
from distutils.sysconfig import get_config_vars
from distutils.version import LooseVersion
import platform

def is_platform_mac():
    return sys.platform == "darwin"

# Build for at least macOS 10.9 when compiling on a 10.9 system or above,
# overriding CPython distuitls behaviour which is to target the version that
# python was built for. This may be overridden by setting
# MACOSX_DEPLOYMENT_TARGET before calling setup.py
if is_platform_mac():
    if "MACOSX_DEPLOYMENT_TARGET" not in os.environ:
        current_system = platform.mac_ver()[0]
        python_target = get_config_vars().get(
            "MACOSX_DEPLOYMENT_TARGET", current_system
        )
        if (
            LooseVersion(python_target) < "10.9"
            and LooseVersion(current_system) >= "10.9"
        ):
            os.environ["MACOSX_DEPLOYMENT_TARGET"] = "10.9"

    if sys.version_info[:2] == (3, 8):  # GH 33239
        extra_compile_args.append("-Wno-error=deprecated-declarations")
```

However, I don't know all the edge cases the pandas solution solves, I think just setting `os.environ["MACOSX_DEPLOYMENT_TARGET"] = "10.9"` is usually sufficient.

I think this is related to a change in C++ libraries on macOS, prior to 10.9 it was `libstdc++`, after it's `libc++`, but I don't write C++ code myself so I'm not entirely sure. This fixes it however.

I had a separate issue trying to `pip install` via a HPC: `    ImportError: libffi.so.6: cannot open shared object file: No such file or directory`

One possible broader solution to this is to use something like: https://github.com/joerick/cibuildwheel

I've recently been trying this on another project. It pre-builds binary wheels across all common platforms (Windows, Mac, Linux) in CI, e.g. within GitHub Actions, which you can then upload as part of your normal release. This would save the user having to compile `auguste` themselves when they pip install.

**Comment by pmla** [comment]
@mkhorton could you check if the installation is working properly? If it works I will release a new version on PyPI.

**Comment by mkhorton** [comment]
Can confirm this works now on macOS

**Comment by pmla** [comment]
I have pushed a new version on PyPI.

Thanks for your help with getting this fixed!

**Comment by pmla** [comment]
I googled the error you got from the HPC. Perhaps this will help?

https://jackiechen.org/2016/01/13/importerror-libffi-so-6-cannot-open-shared-object-file-no-such-file-or-directory/

**Comment by mkhorton** [comment]
No worries, thanks for fixing so promptly!

And yes, I'll try and track down the other error. Will post back if I get it fixed. I fairly routinely install Python codes with C/C++ extensions on that HPC, but it could just be a recent software update has broken something.
